name: Build
concurrency:
  group: "${{ github.repository }}${{ github.ref }}-release"

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: 353146681200.dkr.ecr.us-east-1.amazonaws.com/otterize
  REPOSITORY_NAME: otterize

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}