name: Build
concurrency:
  group: "${{ github.repository }}${{ github.ref }}-release"

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: 353146681200.dkr.ecr.us-east-1.amazonaws.com/otterize
  REPOSITORY_NAME: otterize

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - name: Config creds for private repo
        run: |-
          git config --global url."https://${{ secrets.OTTERIZEBOT_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Install UPX
        run: sudo apt install -y upx

      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.OTTERIZEBOT_GITHUB_TOKEN }}